# This is a basic workflow to help you get started with Actions
name: BasicWorkflow

# Controls when the workflow will run
on:
  issues:
    types:
      - opened

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  my_first_job:
    runs-on: ubuntu-latest
    name: We test it locally with act
    steps:
    - name: REST API with curl
      run: |
        curl -X GET "https://gorest.co.in/public/v2/users"
